[workspace]
resolver = "2"
members = ["projects/*", "examples/*"]
default-members = [
    "projects/acorn-core",
    "projects/acorn-source",
    "projects/acorn-probe",
    "examples/acorn-zip",
    "examples/acorn-docx",
    "examples/acorn-epub",
]
exclude = [
    "projects/.DS_Store",
    "projects/syntax-error",
]

[workspace.package]
version = "0.0.1"
authors = ["Yggdrasill Team <192607617@qq.com>"]
edition = "2021"
license = "MPL-2.0"
homepage = "https://github.com/yggdrasil-language/acorn.rs"
repository = "https://github.com/yggdrasil-language/acorn.rs"

[workspace.dependencies]
thiserror = "2.0.18"
miette = "7.6.0"
serde = { version = "1.0.228", features = ["derive"] }
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }
flate2 = { version = "1.1.5", default-features = false, features = ["rust_backend"] }
diagnostic = { git = "https://github.com/oovm/rust-boost", branch = "dev", package = "diagnostic", default-features = false, features = ["std", "serde"] }

acorn-core = { path = "projects/acorn-core" }
acorn-source = { path = "projects/acorn-source" }
acorn-probe = { path = "projects/acorn-probe" }
acorn-zip = { path = "examples/acorn-zip" }
acorn-cfb = { path = "examples/acorn-cfb" }
acorn-doc = { path = "examples/acorn-doc" }
acorn-docx = { path = "examples/acorn-docx" }
acorn-epub = { path = "examples/acorn-epub" }
acorn-wasm = { path = "examples/acorn-wasm" }
acorn-jvm = { path = "examples/acorn-jvm" }
acorn-pe = { path = "examples/acorn-pe" }
oak-core = { git = "https://github.com/yggdrasil-language/oak.rs.git", branch = "dev", default-features = false, features = ["serde"] }
oak-xml = { git = "https://github.com/yggdrasil-language/oak.rs.git", branch = "dev", default-features = false, features = ["serde"] }

[profile.release]
lto = true
panic = "abort"
