[workspace]
resolver = "2"
members = ["projects/*", "examples/*"]
default-members = [
    "projects/acorn-core",
    "projects/acorn-diagnostic",
    "projects/acorn-source",
    "projects/acorn-probe",
    "examples/acorn-zip",
]
exclude = [
    "projects/.DS_Store",
    "projects/syntax-error",
]

[workspace.package]
version = "0.0.1"
authors = ["Yggdrasill Team <192607617@qq.com>"]
edition = "2021"
license = "MPL-2.0"
homepage = "https://github.com/yggdrasil-language/acorn.rs"
repository = "https://github.com/yggdrasil-language/acorn.rs"

[workspace.dependencies]
thiserror = "2.0.18"
serde = { version = "1.0.228", features = ["derive"] }

acorn-diagnostic = { path = "projects/acorn-diagnostic" }
acorn-core = { path = "projects/acorn-core" }
acorn-source = { path = "projects/acorn-source" }
acorn-probe = { path = "projects/acorn-probe" }

[profile.release]
lto = true
panic = "abort"
